"""
sazon-screener — generated by meta-agent.
"""

from __future__ import annotations

import logging
from typing import Optional

from dotenv import load_dotenv
from google.adk.agents import LlmAgent
from google.adk.skills import load_skill_from_dir
from google.adk.tools.base_toolset import BaseToolset
from google.adk.tools.skill_toolset import SkillToolset

from .config.llm import FAST_MODEL
from .config.paths import skills_dir
from .config.seed import seed_volume_if_empty
from .guardrails.command_guard import command_guard_callback
from .guardrails.exfil_guard import exfil_guard
from .memory.review_fork import review_fork_callback
from .tools import get_tools
from .prompt.instructions import get_agent_instruction

logger = logging.getLogger(__name__)

load_dotenv()

# First-boot: copy in-repo seeds into runtime paths if they're empty
# (no-op locally; populates a deployment volume on first deploy).
seed_volume_if_empty()


class LazySkillToolset(BaseToolset):
    """SkillToolset wrapper that rebuilds when SKILL.md files change.

    Detects mtime changes under SKILLS_DIR on every get_tools() call and
    rebuilds the underlying SkillToolset if anything was added/changed/removed.
    Lets the agent self-author skills (via author_skill, when --persona is on)
    that become queryable on the *next* invocation — no process restart.
    """

    def __init__(self) -> None:
        super().__init__()
        self._mtime: float = -1.0
        self._inner: Optional[SkillToolset] = None

    def _scan_mtime(self) -> float:
        d = skills_dir()
        if not d.is_dir():
            return 0.0
        latest = d.stat().st_mtime
        for p in d.rglob("SKILL.md"):
            try:
                latest = max(latest, p.stat().st_mtime)
            except OSError:
                continue
        return latest

    def _rebuild_if_needed(self) -> None:
        cur = self._scan_mtime()
        if cur == self._mtime and self._inner is not None:
            return
        d = skills_dir()
        skills = []
        if d.is_dir():
            for skill_dir in sorted(d.iterdir()):
                if skill_dir.is_dir() and (skill_dir / "SKILL.md").exists():
                    try:
                        skills.append(load_skill_from_dir(skill_dir))
                    except Exception as e:
                        logger.warning("Skip skill %s: %s", skill_dir.name, e)
        self._inner = SkillToolset(skills=skills) if skills else None
        self._mtime = cur
        logger.info("Skill toolset rebuilt: %d skills", len(skills))

    async def get_tools(self, readonly_context=None):
        self._rebuild_if_needed()
        if self._inner is None:
            return []
        return await self._inner.get_tools(readonly_context)

    async def close(self):
        if self._inner is not None:
            await self._inner.close()


def _build_tools():
    tools = list(get_tools())
    tools.append(LazySkillToolset())
    return tools


root_agent = LlmAgent(
    model=FAST_MODEL,
    name="sazon_screener",
    description="AI candidate screening agent for Grupo Sazon - a restaurant chain hiring delivery drivers across Spain and Mexico",
    instruction=get_agent_instruction,
    tools=_build_tools(),
    before_tool_callback=[exfil_guard, command_guard_callback],
    # Fire-and-forget memory self-improvement judge (opt-in via
    # NUVEL_MEMORY_REVIEW_FORK=1). Never blocks the reply; the judge runs on
    # the SiblingRunner plugin and has no after_agent chain of its own.
    after_agent_callback=[review_fork_callback],
)
